### PR TITLE
Test product 2.1

### PR DESCRIPTION
**Pull request by themenucha**

### CODE REVIEW

**Comment by themenucha** [comment]
srcclr triggeers

**Comment by ralphbean** [comment]
I need to see a JIRA documenting what you're doing here and for what purpose. I understand the general purpose, but I want to make sure we have a clear link to the documented intent.

Second, I'll need more signoff than usual for this from the CPaaS development team leads, so that we're sure there is awareness of this change.

**Comment by ggallen** [comment]
@ralphbean , see https://issues.redhat.com/browse/CPAAS-2484.

Does this help?

**Comment by ralphbean** [comment]
Closing this in favor of https://github.com/continuous-prod/reference-addon/pull/19

**Pull request closed without merging**
